version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cgh
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: shell_scripts/after_install.sh
      timeout: 900
      runas: root