version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd analytics/frontend
      - npm ci

  build:
    commands:
      - echo "Using API URL: $VITE_API_URL"
      - export VITE_API_URL=$VITE_API_URL
      - npm run build

artifacts:
  files:
    - analytics/frontend/dist/**/*
    - analytics/backend/**/*
    - analytics/requirements.txt
    - appspec.yml
    - scripts/**/*
